# Generated by Django 3.0.8 on 2021-05-26 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='phone_list',
        ),
    ]
